version: '3.3'

volumes:
  pg_data:

services:

  db:
    image: postgres:13
    network_mode: host
    ports:
      - 5432:5432
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/